name: audio_video_progress_bar
description: A progress bar widget to show or change the position of an audio or video stream.
version: 0.2.0-nullsafety.0
homepage: https://github.com/suragch/audio_video_progress_bar

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

flutter:
